services:
  mysql:
    image: mysql:latest
    container_name: blog_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      TZ: Asia/Tokyo
    ports:
      - 3306:3306